BEGIN;

CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  email VARCHAR(120) UNIQUE NOT NULL,
  role VARCHAR(16) NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tipos_arma (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS armas (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  tipo_id INT REFERENCES tipos_arma(id) ON DELETE SET NULL,
  rareza SMALLINT NOT NULL DEFAULT 1 CHECK (rareza BETWEEN 1 AND 5),
  peso NUMERIC(5,2) NOT NULL DEFAULT 0,
  escalado VARCHAR(40),
  descripcion TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_armas_nombre ON armas (nombre);
CREATE INDEX IF NOT EXISTS idx_armas_tipo_id ON armas (tipo_id);

CREATE TABLE IF NOT EXISTS clases (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL UNIQUE,
  enfoque VARCHAR(80) NOT NULL,
  vigor SMALLINT NOT NULL DEFAULT 10,
  mente SMALLINT NOT NULL DEFAULT 10,
  resistencia SMALLINT NOT NULL DEFAULT 10,
  fuerza SMALLINT NOT NULL DEFAULT 10,
  destreza SMALLINT NOT NULL DEFAULT 10,
  inteligencia SMALLINT NOT NULL DEFAULT 10,
  fe SMALLINT NOT NULL DEFAULT 10,
  arcano SMALLINT NOT NULL DEFAULT 10,
  descripcion TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS armaduras (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  categoria VARCHAR(50) NOT NULL,
  peso NUMERIC(5,2) NOT NULL DEFAULT 0,
  defensa_fisica NUMERIC(6,2) NOT NULL DEFAULT 0,
  defensa_magica NUMERIC(6,2) NOT NULL DEFAULT 0,
  descripcion TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS hechizos (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  costo_fp SMALLINT NOT NULL DEFAULT 0,
  requisitos VARCHAR(120),
  descripcion TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS milagros (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  costo_fp SMALLINT NOT NULL DEFAULT 0,
  requisitos VARCHAR(120),
  descripcion TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS talismanes (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  efecto TEXT NOT NULL,
  ubicacion TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS personajes (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  faccion VARCHAR(120),
  zona VARCHAR(120),
  descripcion TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS builds (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  enfoque VARCHAR(80) NOT NULL,
  nivel_recomendado VARCHAR(40),
  distribucion_puntos VARCHAR(180),
  descripcion TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE builds
ADD COLUMN IF NOT EXISTS nivel_recomendado VARCHAR(40);

ALTER TABLE builds
ADD COLUMN IF NOT EXISTS distribucion_puntos VARCHAR(180);

COMMIT;
